# Generated by Django 5.0.7 on 2024-08-10 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('passedout', models.IntegerField()),
                ('achievements', models.TextField(max_length=2000)),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('exp', models.IntegerField()),
                ('workplace', models.CharField(max_length=200)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('portfolio', models.URLField()),
                ('image', models.ImageField(upload_to='media')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
